---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-setup-cm
  namespace: default
data:
  application.yml: |
    spring:
      application:
        name: eureka
    server:
      port: 8761
    eureka:
      client:
        serviceUrl:
          defaultZone: ${EUREKA_SERVER_ADDRESS}
    logging:
      config: ./log4j2.xml
      file: false
      level:
        root: info
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <property resource="bootstrap.yml" />
        <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
        <include resource="org/springframework/boot/logging/logback/console-appender.xml" />

        <root>
            <appender-ref ref="CONSOLE" />
        </root>
    </configuration>
