---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
  - port: 8761
    targetPort: eureka-tp
    name: eureka
  selector:
    app: eureka
